[package]
name = "sithra-onebot"
version = "0.1.0"
edition.workspace = true

[dependencies]
ioevent.workspace = true
tokio.workspace = true
sithra_common.workspace = true
log.workspace = true
thiserror.workspace = true