[package]
name = "sithra-types"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde.workspace = true

# Workspace dependencies

sithra-server.workspace = true
sithra-transport.workspace = true

[lints]
workspace = true
